version: '3.3'
services:
  stores-api:
    build:
      context: .
    command: symfony serve
    volumes:
      - .:/src
      - /src/vendor
    ports:
      - "1002:8000"
    environment:
      - PHP_IDE_CONFIG=serverName=docker

  stores-sync:
    build:
      context: .
    command: php bin/console sync_worker
    volumes:
      - .:/src
      - /src/vendor
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    depends_on:
      - stores-api

  stores-async:
    build:
      context: .
    command: php bin/console async_worker
    volumes:
      - .:/src
      - /src/vendor
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    depends_on:
      - stores-api

  stores-unit-test:
    build:
      context: .
    command: >
      bash -c "echo yes | php bin/console doctrine:fixtures:load > /dev/null
      && vendor/bin/phpunit --bootstrap tests/bootstrap.php --configuration tests/phpunit.xml"
    environment:
      - APP_ENV=test
    volumes:
      - .:/src
      - /src/vendor

networks:
  default:
    external:
      name: marketplace-network